.integration-api:
  rules:
    - if: $CI_PIPELINE_SOURCE != 'web' && $CI_COMMIT_MESSAGE =~ /\[all\]/
    - if: $CI_PIPELINE_SOURCE != 'web' && $CI_COMMIT_MESSAGE =~ /\[integration\]/
    - if: $CI_PIPELINE_SOURCE != 'web' && $CI_COMMIT_MESSAGE !~ /\[gateway\]/ && $CI_COMMIT_MESSAGE !~ /\[identity\]/ && $CI_COMMIT_MESSAGE !~ /\[ecommerce\]/ && $CI_COMMIT_MESSAGE !~ /\[order\]/ && $CI_COMMIT_MESSAGE !~ /\[synchronize\]/ && $CI_COMMIT_MESSAGE !~ /\[integration\]/ && $CI_COMMIT_MESSAGE !~ /\[notification\]/ && $CI_COMMIT_MESSAGE !~ /\[all\]/
      changes:
        - src/services/integration/**/*
    - if: $CI_PIPELINE_SOURCE == "web" && ($SERVICES =~ /integration/ || $SERVICES =~ /all/)

integration-api 1/4:
  extends: .integration-api
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'
  stage: integration-api
  inherit:
    default: false
  tags:
    - dev-vpc-vt
  script:
    - docker build . --build-arg ASPNETCORE_ENVIRONMENT=production -f src/services/integration/Integration.Api/Dockerfile -t ${DOCKER_PREFIX_STAGING}integration-api:latest

integration-api 2/4:
  extends: .integration-api
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'
  needs: [integration-api 1/4]
  stage: integration-api
  tags:
    - dev-vpc-vt
  script:
    - docker push ${DOCKER_PREFIX_STAGING}integration-api:latest

integration-api 3/4:
  extends: .integration-api
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'
  needs: [integration-api 2/4]
  stage: integration-api
  tags:
    - dev-vpc-vt
  script:
    - docker-compose -f $COMPOSE_FILE pull integration-api

integration-api 4/4:
  extends: .integration-api
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'
  needs: [integration-api 3/4]
  stage: integration-api
  inherit:
    default: false
  tags:
    - dev-vpc-vt
  script:
    - docker-compose -f $COMPOSE_FILE   up -d integration-api

